name: Python Lint and Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Format with black
        uses: psf/black@stable
        with:
          args: .
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Lint with ruff
        run: poetry run ruff --exit-non-zero-on-fix .
      - name: Test with pytest
        run: poetry run pytest
      - name: Compare docs
        run: | 
          poetry run pdoc crossense -o ./docs_new
          diff ./docs ./docs_new || exit 1